# Site
name: "Paula Demarco"
title: "Paula Demarco"
description: "Sorghum research"
logo: 'assets/images/logo_pj.png'
favicon: 'assets/images/logo1.png'
#baseurl: /jekyll-theme-memoirs
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: pademarco@ksu.edu

# Authors
authors:
  sal:
    name: Paula Demarco
    display_name: Paula
    avatar: 'assets/images/avatar-pau.png'
    email: pademarco@ksu.edu
    web: https://www.PaulaDemarco.github.io
    twitter: https://twitter.com/PaulaADemarco
    description: "M.Sc. in Agronomy. Graduate Research Assistant at Kansas State University."
  john:
    name: Javier
    display_name: Javier    
    avatar: 'assets/images/avatar-javi.png'
    email: jafernandez@ksu.edu
    web: https://www.jafernandez.netlify.app
    twitter: https://twitter.com/Jav1erFernandez
    description: "Ph.D. in Agronomy. Graduate Research Assistant at Kansas State University."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
